toggler
js-tasks-ru/htmlcss-20230530_jakubaites pull request #19
Opened 2023-06-29 11:37 UTC by Jakubaites

2023-06-29 11:38 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-06-30 20:56 UTC, GSemikozov requested changes

2023-06-30 20:56 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +    left: 2px;
сверху тоже 2?

2023-07-01 10:11 UTC, Jakubaites commented on 07-lection5/03-toggler/toggler.css
> +    left: 2px;
В родителе установил: 
    display: flex;
    align-items: center;
Это сработало и выставило шарик по вертикали по центру. Хотя и позиция у шарика absolute

2023-07-01 10:30 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +    left: 2px;
нет, это не флекс выравнивает) в общем, когда позиционируем абсолютом - то лучше все таки задавать четкие координаты слева/сверху | снизу/справа

2023-07-01 10:39 UTC, Jakubaites commented on 07-lection5/03-toggler/toggler.css
> +    left: 2px;
Я тоже был удивлен, что это работало, ведь при абсолюте мы вытаскиваем элемент из контекста и позиционируем отдельно

2023-07-01 10:41 UTC, GSemikozov approved these changes

2023-07-01 10:41 UTC, merged