input text
js-tasks-ru/htmlcss-20230530_jakubaites pull request #20
Opened 2023-06-30 11:17 UTC by Jakubaites

2023-06-30 11:17 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-30 20:59 UTC, GSemikozov requested changes

2023-06-30 20:59 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +      <label class="input">
в случае с данным блоком все заворачивать в лейбл не надо)

2023-06-30 20:59 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +        <p class="input__header">LABEL</p>
вот это и есть label

2023-06-30 20:59 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +       <input type="text" class="input__text" placeholder="Placeholder">
а вот инпут вместе с иконками лучше завернуть в общий враппер с position: relative, чтобы позиционировать иконки относительно только инпута

2023-06-30 20:59 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +       <svg class="input__successImg" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
`input__icon nput__icon_success`

2023-06-30 20:59 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    width: 350px;
как вариант min-width

2023-06-30 20:59 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__successImg {
.input__iocn, позиционирование одинаковое, только показываем разные в зависимости от модификатора блока

2023-07-01 10:22 UTC, Jakubaites commented on 07-lection5/04-input/index.html
> +      <label class="input">
Ok

2023-07-01 10:26 UTC, Jakubaites commented on 07-lection5/04-input/index.html
> +        <p class="input__header">LABEL</p>
Ok

2023-07-01 10:28 UTC, Jakubaites commented on 07-lection5/04-input/index.html
> +       <input type="text" class="input__text" placeholder="Placeholder">
ok

2023-07-01 10:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-07-01 11:00 UTC, Jakubaites commented on 07-lection5/04-input/index.html
> +       <svg class="input__successImg" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
Ok

2023-07-01 11:00 UTC, Jakubaites commented on 07-lection5/04-input/input.css
> +    width: 350px;
сделано

2023-07-01 11:05 UTC, Jakubaites commented on 07-lection5/04-input/input.css
> +.input__successImg {
Переписал, в зависимости от модификатора блока.

2023-07-01 11:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-07-02 02:45 UTC, GSemikozov requested changes

2023-07-02 02:45 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +          LABEL
текст надо завернуть в label и связать label с input через id + for

2023-07-02 02:45 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    font-family: 'Inter';
текстовые стили будут в .input__label

2023-07-02 09:38 UTC, Jakubaites commented on 07-lection5/04-input/index.html
> +          LABEL
Готово

2023-07-02 09:38 UTC, Jakubaites commented on 07-lection5/04-input/input.css
> +    font-family: 'Inter';
Готово

2023-07-02 09:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-07-05 20:45 UTC, GSemikozov approved these changes

2023-07-05 20:45 UTC, merged