create index page
js-tasks-ru/htmlcss-20230530_jakubaites pull request #4
Opened 2023-06-08 16:36 UTC by Jakubaites

2023-06-08 16:37 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-09 13:53 UTC, GSemikozov requested changes

2023-06-09 13:53 UTC, GSemikozov commented on components/footer/footer.css
> +    height: 250px;
высоту фиксировать не стоит

2023-06-09 13:53 UTC, GSemikozov commented on components/header/header.css
> +@import '../fonts/fonts.css'; /*Добавляем шрифт Inter*/
импортировать в компоненты не надо, шрифты и так подключаются глобально в main.css

2023-06-10 11:03 UTC, Jakubaites commented on components/footer/footer.css
> +    height: 250px;
Исправлено)

2023-06-10 11:03 UTC, Jakubaites commented on components/header/header.css
> +@import '../fonts/fonts.css'; /*Добавляем шрифт Inter*/
Редактировано

2023-06-10 12:08 UTC, GSemikozov approved these changes

2023-06-10 12:08 UTC, merged